### ISSUE TITLE
Dungeons Crash

### ISSUE THREAD

**Issue by zenblob** [Betalord/BHBot#50]
Good morning,
It often happens to me that the programs stop this way.
It runs on a virtual machine, it may be slow, sometimes I get the impression that the error is written to the console an instant before the team selection screen opens
![error](https://user-images.githubusercontent.com/48311971/55708356-01db2500-59e6-11e9-810c-13e4ce68b873.PNG)
![errorscr](https://user-images.githubusercontent.com/48311971/55708537-73b36e80-59e6-11e9-9163-92fa1cdb4347.PNG)

**Comment by ilpersi** [comment]
I unintentionally closed this with the latest commit, so I am reopening this.

I've added some better checks in the current code base, will test them in the next couple of days.

**Comment by Larrush** [comment]
Had the same Issue today, or a very similiar one with the newest master

```
<2019/04/09 00:35:57> BHBot v34.2 started.
<2019/04/09 00:35:57> Found 12 familiar cue(s) with old format.
<2019/04/09 00:35:57> Found 78 familiar cue(s) with new format.
<2019/04/09 00:35:57> Settings loaded from file
<2019/04/09 00:35:57> Character: WckedL
<2019/04/09 00:35:57> Found Chromium in C:\Users\Larry\AppData\Local\Chromium\Application\chrome.exe
<2019/04/09 00:35:57> Found chromedriver in C:\Users\Larry\Desktop\BHBot-34.2\chromedriver.exe
<2019/04/09 00:35:57> Found cues in C:\Users\Larry\Desktop\BHBot-34.2\cues
<2019/04/09 00:35:57> Found screenshots in C:\Users\Larry\Desktop\BHBot-34.2\screenshots
<2019/04/09 00:35:57> Driver started succesfully
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 24520
Only local connections are allowed.
<2019/04/09 00:36:14> Game element found. Starting to run bot..
<2019/04/09 00:36:39> News popup dismissed.
<2019/04/09 00:36:55> One time check to make sure that ignore shrines/boss is disabled
<2019/04/09 00:36:58> autoShrine disabled
<2019/04/09 00:37:01> Shards: 0, required: >0
<2019/04/09 00:37:04> Expedition button not found
<2019/04/09 00:37:08> Tokens: 2, required: >0
<2019/04/09 00:37:10> Energy: 14%, required: >4%
java.lang.NumberFormatException: For input string: "33,"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at MainThread.decideDungeonRandomly(MainThread.java:4672)
        at MainThread.run(MainThread.java:1782)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by Larrush** [comment]
I think this also happens to me.
I have the newest master.

```
<2019/04/09 14:06:08> Trials completed successfully. Result: Victory
<2019/04/09 14:06:09> Energy: 51%, required: >0%
java.lang.NumberFormatException: For input string: "33,"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at MainThread.decideDungeonRandomly(MainThread.java:4672)
        at MainThread.run(MainThread.java:1782)
        at java.lang.Thread.run(Unknown Source)
```

Thanks for looking at this! :)

**Comment by ilpersi** [comment]
@Larrush 
Your error is different from zenblob one. Please doublecheck your dungeons value in settings.ini. You should have no comma in it.

**Comment by Larrush** [comment]
Omg 🤦‍♂️
I should have read the line before posting it.
Thanks for the quick solution!

**Comment by ilpersi** [comment]
I've added some better fail safe in the latest commits so I am closing this. If this happens again, please log another issue.
